### ISSUE TITLE
Due Dates

### ISSUE THREAD

**Issue by rsmease** [rsmease/ashai#12]
- [ ] Backend: model, controller, views
- [ ] Redux cycle: ajax, actions, reducer
- [ ] Presentational Components
- [ ] Styling
- [ ] Smooth, bug-free navigation
- [ ] Update demo seeds to include feature
