### ISSUE TITLE
Subtasks

### ISSUE THREAD

**Issue by rsmease** [rsmease/ashai#9]
- [ ] Backend: update Task model, controller and views
- [ ] Redux cycle: ajax, actions, creators
- [ ] Styling
- [ ] Smooth, bug-free navigation
- [ ] Manually seeded Game of Thrones-related data
